### ISSUE TITLE
Failed to resolve: one.block:eosioandroidkeystoresignatureprovider:0.1.0

### ISSUE THREAD

**Issue by shamtroon** [EOSIO/eosio-android-keystore-signature-provider#17]
Hi guys, initially I worked on "one.block:eosiojavasoftkeysignatureprovider" which worked correctly in my Android application. Now I want to use "eosio-android-keystore-signature-provider", for this purpose, I add this "one.block:eosioandroidkeystoresignatureprovider:0.1.0" dependency in "build.gradle (app)", but now my project show error on sync. 

Error : "ERROR: Failed to resolve: one.block:eosioandroidkeystoresignatureprovider:0.1.0"

**Comment by DanteNguyen1008** [comment]
Thanks for the report. We are solving the issue. Will let you know when we are done.

**Comment by DanteNguyen1008** [comment]
The issue was fixed. Please try to sync your gradle again.

**Comment by shamtroon** [comment]
Thanks @DanteNguyen1008 , now issue is resolved.

**Comment by DanteNguyen1008** [comment]
Yes, Please checkout https://t.me/eoswalletdev
